# NumPy Practice Questions

**Instructions:** Dear Students Each question is self‑explanatory. Read the markdown prompt and write the code in the cell below it where marked `# answer here`. Keep solutions simple and focused on the asked concept.

- Q1–Q30: Single-topic questions in sequence (basics → indexing → operations → aggregations → reshaping/broadcasting → utilities).

- Q31–Q35: Multi‑concept (combine 2–3 ideas you practiced).

- Q36–Q40: Use a single dataset loaded via **pandas** and perform **NumPy** operations on it. The file `students_scores.csv` is already available in the same folder as this notebook.


### Q1. Create a 1D NumPy array from the Python list `[1, 2, 3, 4, 5]` and print its type and contents.

In [1]:
# answer here
import numpy as np
list1 = [1,2,3,4,5]
numpy_array = np.array(list1)
numpy_array

array([1, 2, 3, 4, 5])

### Q2. Create a 2D NumPy array from `[[1, 2, 3], [4, 5, 6]]` and print its `shape` and `ndim`.

In [4]:
# answer here
numpy_array2 = np.array([[1,2,3],[4,5,6]])
print(numpy_array2)
print(numpy_array2.shape)
print(numpy_array2.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2


### Q3. Create an array of 6 zeros and print it.

In [5]:
# answer here
numpy_array3 = np.zeros(6)
numpy_array3

array([0., 0., 0., 0., 0., 0.])

### Q4. Create an array of 5 ones (float) and print it.

In [6]:
# answer here
numpy_array4 = np.ones(5)
numpy_array4

array([1., 1., 1., 1., 1.])

### Q5. Use `np.arange` to create an array from 2 to 14 (inclusive of 2, exclusive of 14) with a step of 2 and print it.

In [7]:
# answer here
numpy_array5 = np.arange(2,14,2)
numpy_array5

array([ 2,  4,  6,  8, 10, 12])

### Q6. Use `np.linspace` to create 5 evenly spaced values from 0 to 1 and print them.

In [8]:
# answer here
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Q7. Create an integer array `[10, 20, 30]` then convert it to `float` dtype and print both arrays.

In [10]:
# answer here
array = np.array([10,20,30])
float_array = array.astype(float)
print(array)
print(float_array)

[10 20 30]
[10. 20. 30.]


### Q8. Create an array of 12 numbers from 0 to 11 and reshape it to `3x4`; print the reshaped array.

In [11]:
# answer here
numpy_array5 = np.arange(12).reshape(3,4)
numpy_array5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Q9. For the array `a = np.array([[1,2,3],[4,5,6]])`, print `a.shape`, `a.ndim`, and `a.size`.

In [12]:
# answer here
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)
print(a.ndim)
print(a.size)

(2, 3)
2
6


### Q10. For the array `a = np.array([1,2,3], dtype=np.int32)`, print `a.dtype` and `a.itemsize`.

In [13]:
# answer here
a2 = np.array([1,2,3])
print(a.dtype)
print(a.itemsize)

int64
8


### Q11. Given `arr = np.array([10, 20, 30, 40, 50])`, print the first element, last element, and the element at index 2.

In [15]:
# answer here
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])
print(arr[-1])
print(arr[2])

10
50
30


### Q12. Given `arr = np.array([5, 10, 15, 20, 25])`, use negative indexing to print the last two elements.

In [16]:
# answer here
arr2 = np.array([5, 10, 15, 20, 25])
print(arr2[-1])
print(arr2[-2])

25
20


### Q13. Given `arr = np.array([0,1,2,3,4,5,6,7,8,9])`, print the slice from index 2 to 7 (exclusive).

In [18]:
# answer here
arr = np.array([0,1,2,3,4,5,6,7,8,9])
print(arr[2:7])

[2 3 4 5 6]


### Q14. Given `m = np.arange(1,13).reshape(3,4)`, print the second row and the third column (as 1D slices).

In [24]:
# answer here
m = np.arange(1,13).reshape(3,4)
print(m[1:2, 2:3])

[[7]]


### Q15. Given `m = np.arange(1,13).reshape(3,4)`, print the submatrix containing rows 0 to 1 and columns 1 to 3.

In [22]:
# answer here
m = np.arange(1,13).reshape(3,4)
m[0:2,1:]

array([[2, 3, 4],
       [6, 7, 8]])

### Q16. Given `arr = np.arange(1,11)`, create a boolean mask for even numbers and print the even elements.

In [25]:
# answer here
arr3 = np.arange(1,11)
mask = arr3 % 2 == 0

print(arr3[mask])

[ 2  4  6  8 10]


### Q17. Given `arr = np.arange(1,11)`, set all odd elements to `-1` (modify in place) and print the result.

In [27]:
# answer here
odd = arr3 %2 != 0
arr3[odd] = -1
print(arr3)

[-1  2 -1  4 -1  6 -1  8 -1 10]


### Q18. Given `arr = np.array([1,2,3])`, add `5` to every element and print the result (element‑wise).

In [28]:
# answer here
arr4 = np.array([1,2,3])
arr4 + 5

array([6, 7, 8])

### Q19. Given `a = np.array([1,2,3])` and `b = np.array([4,5,6])`, print `a + b` and `a * b` (element‑wise).

In [30]:
# answer here
b = np.array([4,5,6])
print(arr4 + b)
print(arr4 * b)

[5 7 9]
[ 4 10 18]


### Q20. Given `a = np.array([1,2,3])` and `b = np.array([[10],[20],[30]])`, use broadcasting to compute `a + b` and print it.

In [32]:
# answer here
arr5 = np.array([1,2,3])
arr6 = np.array([[10],[20],[30]])
print(arr5 + arr6)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


### Q21. Given `arr = np.array([3, 7, 2, 9, 5])`, print its `sum`, `mean`, `min`, and `max`.

In [36]:
# answer here
arr7 = np.array([3, 7, 2, 9, 5])
print("sum",np.sum(arr7))
print("mean",np.mean(arr7))
print("min",np.min(arr7))
print("max",np.max(arr7))

sum 26
mean 5.2
min 2
max 9


### Q22. Given `m = np.arange(1,13).reshape(3,4)`, print the sum along axis 0 and along axis 1.

In [38]:
# answer here
print("sum along axis 0",np.sum(m,axis=0))
print("sum along axis 1",np.sum(m,axis=1))

sum along axis 0 [15 18 21 24]
sum along axis 1 [10 26 42]


### Q23. Given `arr = np.array([10, 20, 5, 40, 25])`, print the indices of the `max` and `min` elements using `np.argmax` and `np.argmin`.

In [39]:
# answer here
arr8 = np.array([10, 20, 5, 40, 25])
print(np.argmax(arr8))
print(np.argmin(arr8))

3
2


### Q24. Given `arr = np.array([3, 3, 1, 2, 2, 2, 5])`, print the sorted array and the unique values using `np.unique`.

In [43]:
# answer here
arr9 = np.array([3, 3, 1, 2, 2, 2, 5])
print(np.sort(arr9))
print(np.unique(arr9))

[1 2 2 2 3 3 5]
[1 2 3 5]


### Q25. Given `arr = np.array([9, 1, 5, 3, 7])`, sort it in ascending order and print the result (do not modify original).

In [46]:
# answer here
arr10 = np.array([9, 1, 5, 3, 7])
sort_arr10 = np.sort(arr10)
print(sort_arr10)

[1 3 5 7 9]


### Q26. Given `a = np.array([1,2,3])` and `b = np.array([4,5,6])`, horizontally concatenate them and print the result.

In [49]:
# answer here
arr11 = np.array([1,2,3])
arr12 = np.array([4,5,6])
print(np.hstack((arr11, arr12)))

[1 2 3 4 5 6]


### Q27. Given `A = np.array([[1,2],[3,4]])` and `B = np.array([[5,6],[7,8]])`, stack them vertically and print the result.

In [50]:
# answer here
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(np.vstack((A,B)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### Q28. Given `arr = np.arange(1,13)`, split it into 3 equal parts and print each part.

In [72]:
# answer here
arr13 = np.arange(1,13)
parts = np.split(arr13, 3)

for i in parts:
  print(i)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


### Q29. Set a random seed (e.g., 42), generate 5 random integers from 0 to 9 using `np.random.randint`, and print them.

In [81]:
# answer here
np.random.seed(42)
arr14 = np.random.randint(0, 10, 5)
print(arr14)

[0 9 2 6 3]


### Q30. Given `arr = np.array([-3, 1, -1, 4, -2, 5])`, use `np.where` to replace negative values with `0` and print the new array.

In [82]:
# answer here
arr15 = np.array([-3, 1, -1, 4, -2, 5])
new_arr = np.where(arr15 < 0, 0, arr15)
new_arr

array([0, 1, 0, 4, 0, 5])

### Q31. Create a 3D array of shape `(2, 3, 4)` using `np.arange` then compute the mean along axis 2 and print the result.

In [84]:
# answer here
arr16 = np.arange(24).reshape(2,3,4)
np.mean(arr16,axis=2)

array([[ 1.5,  5.5,  9.5],
       [13.5, 17.5, 21.5]])

### Q32. Create an array from `[5, 10, 15, 20, 25]`, slice out `[10, 15, 20]`, then normalize that slice to range 0–1 using min‑max formula and print it.

In [92]:
# answer here
arr17 = np.array([5, 10, 15, 20, 25])
slice_arr = arr17[1:4]
normalize = (slice_arr - slice_arr.min())/(slice_arr.max()-slice_arr.min())
normalize

array([0. , 0.5, 1. ])

### Q33. Create two 1D arrays `a=[1,2,3]` and `b=[4,5,6]`; compute the dot product and also form a `3x2` matrix from `a` and `b` and print both results.

In [93]:
# answer here
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

dot_product = np.dot(a, b)

matrix = np.column_stack((a, b))

print("Dot product:", dot_product)
print("3x2 Matrix:\n", matrix)


Dot product: 32
3x2 Matrix:
 [[1 4]
 [2 5]
 [3 6]]


### Q34. Create an array of 12 values (1–12), reshape it to `3x4`, then count how many values are greater than `6` and print the count.

In [98]:
# answer here
arr18 = np.arange(1,13).reshape(3,4)
ans = arr18 > 6
print(arr18[ans])

[ 7  8  9 10 11 12]


### Q35. Create an array from 0–9; replace all odd numbers with `-1` *except* keep the first and last elements unchanged; print the final array.

In [105]:
# answer here
arr19 = np.arange(0,10)
arr19[1:-1] = np.where(arr19[1:-1] % 2 != 0, -1, arr19[1:-1])
print(arr19)

[ 0 -1  2 -1  4 -1  6 -1  8  9]


### Dataset for Q36–Q40

A CSV file **`students_scores.csv`** is already placed in this folder (Link-https://drive.google.com/file/d/1B7zDahhmQzXkQmvskS27H07B4Xftf9xA/view?usp=sharing).  

Columns: `id, math, english, science` (10 students). Use **pandas** to import the file and then perform **NumPy** operations.


### Q36. Import `students_scores.csv` as a pandas DataFrame `df`. Then convert the `math`, `english`, and `science` columns to separate NumPy arrays and print their shapes.

In [110]:
# answer here
import pandas as pd

students_score = pd.read_csv('/content/students_scores.csv')
math_array = students_score['math'].to_numpy()
english_array = students_score['english'].to_numpy()
science_array = students_score['science'].to_numpy()

print(math_array.shape)
print(english_array.shape)
print(science_array.shape)

(10,)
(10,)
(10,)


### Q37. Using NumPy on the arrays from Q36, compute the mean score of each subject (math, english, science) and print them.

In [111]:
# answer here
print(math_array.mean())
print(english_array.mean())
print(science_array.mean())

70.3
69.5
70.1


### Q38. Using NumPy, compute each student’s **total score** (math + english + science) and print the `id` of the student with the highest total.

In [113]:
# answer here
total_scores = math_array + english_array + science_array

top_student_index = np.argmax(total_scores)

print("Total scores:", total_scores)
print("ID of top student:", top_student_index)

Total scores: [215 186 259 148 253 200 219 181 251 187]
ID of top student: 2


### Q39. Using NumPy, standardize the `math` scores to **z-scores**: `(x - mean) / std` and print the first 5 standardized values.

In [116]:
# answer here
mean = np.mean(math_array)
std = np.std(math_array)

# Standardize to z-scores
z_scores = (math_array - mean) / std

# Print first 5 standardized values
print(z_scores[:5])

[ 0.53032869 -0.98489614  1.21906724 -1.74250855  1.49456267]


In [ ]:
# this is how you can approach question number 39
# dont fear about std(standard deviation , just google it and you understand its simple, else you can connect for doubts)


import pandas as pd
import numpy as np

# Load the dataset
df = pd.read_csv("students_scores.csv")

# Extract math column as NumPy array
math_scores = df["math"].values

# Compute z-scores
z_scores = (math_scores - np.mean(math_scores)) / np.std(math_scores)

# Print first 5 standardized values
print(z_scores[:5])


### Q40. Using NumPy logical operations, count how many students scored **≥ 70 in all three subjects** and print that count.

In [118]:
# answer here
passed_all = (math_array >= 70) & (english_array >= 70) & (science_array >= 70)

count = np.sum(passed_all)
count

np.int64(3)